// Generated by gencpp from file chusa_msgs/3DSensingOnce.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_3DSENSINGONCE_H
#define CHUSA_MSGS_MESSAGE_3DSENSINGONCE_H

#include <ros/service_traits.h>


#include <chusa_msgs/3DSensingOnceRequest.h>
#include <chusa_msgs/3DSensingOnceResponse.h>


namespace chusa_msgs
{

struct 3DSensingOnce
{

typedef 3DSensingOnceRequest Request;
typedef 3DSensingOnceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct 3DSensingOnce
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::3DSensingOnce > {
  static const char* value()
  {
    return "660c3f339f7375b5b07c1dde2dac1418";
  }

  static const char* value(const ::chusa_msgs::3DSensingOnce&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::3DSensingOnce > {
  static const char* value()
  {
    return "chusa_msgs/3DSensingOnce";
  }

  static const char* value(const ::chusa_msgs::3DSensingOnce&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::3DSensingOnceRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::3DSensingOnce > 
template<>
struct MD5Sum< ::chusa_msgs::3DSensingOnceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::3DSensingOnce >::value();
  }
  static const char* value(const ::chusa_msgs::3DSensingOnceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::3DSensingOnceRequest> should match 
// service_traits::DataType< ::chusa_msgs::3DSensingOnce > 
template<>
struct DataType< ::chusa_msgs::3DSensingOnceRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::3DSensingOnce >::value();
  }
  static const char* value(const ::chusa_msgs::3DSensingOnceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::3DSensingOnceResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::3DSensingOnce > 
template<>
struct MD5Sum< ::chusa_msgs::3DSensingOnceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::3DSensingOnce >::value();
  }
  static const char* value(const ::chusa_msgs::3DSensingOnceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::3DSensingOnceResponse> should match 
// service_traits::DataType< ::chusa_msgs::3DSensingOnce > 
template<>
struct DataType< ::chusa_msgs::3DSensingOnceResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::3DSensingOnce >::value();
  }
  static const char* value(const ::chusa_msgs::3DSensingOnceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_3DSENSINGONCE_H
