// Generated by gencpp from file chusa_msgs/TfFromTilt.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_TFFROMTILT_H
#define CHUSA_MSGS_MESSAGE_TFFROMTILT_H

#include <ros/service_traits.h>


#include <chusa_msgs/TfFromTiltRequest.h>
#include <chusa_msgs/TfFromTiltResponse.h>


namespace chusa_msgs
{

struct TfFromTilt
{

typedef TfFromTiltRequest Request;
typedef TfFromTiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TfFromTilt
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::TfFromTilt > {
  static const char* value()
  {
    return "0bcecc00ec52f2816884a23e17cf9156";
  }

  static const char* value(const ::chusa_msgs::TfFromTilt&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::TfFromTilt > {
  static const char* value()
  {
    return "chusa_msgs/TfFromTilt";
  }

  static const char* value(const ::chusa_msgs::TfFromTilt&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::TfFromTiltRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::TfFromTilt > 
template<>
struct MD5Sum< ::chusa_msgs::TfFromTiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::TfFromTilt >::value();
  }
  static const char* value(const ::chusa_msgs::TfFromTiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::TfFromTiltRequest> should match 
// service_traits::DataType< ::chusa_msgs::TfFromTilt > 
template<>
struct DataType< ::chusa_msgs::TfFromTiltRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::TfFromTilt >::value();
  }
  static const char* value(const ::chusa_msgs::TfFromTiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::TfFromTiltResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::TfFromTilt > 
template<>
struct MD5Sum< ::chusa_msgs::TfFromTiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::TfFromTilt >::value();
  }
  static const char* value(const ::chusa_msgs::TfFromTiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::TfFromTiltResponse> should match 
// service_traits::DataType< ::chusa_msgs::TfFromTilt > 
template<>
struct DataType< ::chusa_msgs::TfFromTiltResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::TfFromTilt >::value();
  }
  static const char* value(const ::chusa_msgs::TfFromTiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_TFFROMTILT_H
