// Generated by gencpp from file chusa_msgs/TiltClkWise.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_TILTCLKWISE_H
#define CHUSA_MSGS_MESSAGE_TILTCLKWISE_H

#include <ros/service_traits.h>


#include <chusa_msgs/TiltClkWiseRequest.h>
#include <chusa_msgs/TiltClkWiseResponse.h>


namespace chusa_msgs
{

struct TiltClkWise
{

typedef TiltClkWiseRequest Request;
typedef TiltClkWiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TiltClkWise
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::TiltClkWise > {
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::chusa_msgs::TiltClkWise&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::TiltClkWise > {
  static const char* value()
  {
    return "chusa_msgs/TiltClkWise";
  }

  static const char* value(const ::chusa_msgs::TiltClkWise&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::TiltClkWiseRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::TiltClkWise > 
template<>
struct MD5Sum< ::chusa_msgs::TiltClkWiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::TiltClkWise >::value();
  }
  static const char* value(const ::chusa_msgs::TiltClkWiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::TiltClkWiseRequest> should match 
// service_traits::DataType< ::chusa_msgs::TiltClkWise > 
template<>
struct DataType< ::chusa_msgs::TiltClkWiseRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::TiltClkWise >::value();
  }
  static const char* value(const ::chusa_msgs::TiltClkWiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::TiltClkWiseResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::TiltClkWise > 
template<>
struct MD5Sum< ::chusa_msgs::TiltClkWiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::TiltClkWise >::value();
  }
  static const char* value(const ::chusa_msgs::TiltClkWiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::TiltClkWiseResponse> should match 
// service_traits::DataType< ::chusa_msgs::TiltClkWise > 
template<>
struct DataType< ::chusa_msgs::TiltClkWiseResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::TiltClkWise >::value();
  }
  static const char* value(const ::chusa_msgs::TiltClkWiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_TILTCLKWISE_H
