// Generated by gencpp from file chusa_msgs/StartArduino.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_STARTARDUINO_H
#define CHUSA_MSGS_MESSAGE_STARTARDUINO_H

#include <ros/service_traits.h>


#include <chusa_msgs/StartArduinoRequest.h>
#include <chusa_msgs/StartArduinoResponse.h>


namespace chusa_msgs
{

struct StartArduino
{

typedef StartArduinoRequest Request;
typedef StartArduinoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartArduino
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::StartArduino > {
  static const char* value()
  {
    return "71fc9b1e75ffe5e1ee5282a81d66a2b7";
  }

  static const char* value(const ::chusa_msgs::StartArduino&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::StartArduino > {
  static const char* value()
  {
    return "chusa_msgs/StartArduino";
  }

  static const char* value(const ::chusa_msgs::StartArduino&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::StartArduinoRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::StartArduino > 
template<>
struct MD5Sum< ::chusa_msgs::StartArduinoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::StartArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StartArduinoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::StartArduinoRequest> should match 
// service_traits::DataType< ::chusa_msgs::StartArduino > 
template<>
struct DataType< ::chusa_msgs::StartArduinoRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::StartArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StartArduinoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::StartArduinoResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::StartArduino > 
template<>
struct MD5Sum< ::chusa_msgs::StartArduinoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::StartArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StartArduinoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::StartArduinoResponse> should match 
// service_traits::DataType< ::chusa_msgs::StartArduino > 
template<>
struct DataType< ::chusa_msgs::StartArduinoResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::StartArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StartArduinoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_STARTARDUINO_H
