// Generated by gencpp from file chusa_msgs/StartArduinoRequest.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_STARTARDUINOREQUEST_H
#define CHUSA_MSGS_MESSAGE_STARTARDUINOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct StartArduinoRequest_
{
  typedef StartArduinoRequest_<ContainerAllocator> Type;

  StartArduinoRequest_()
    : min_pwm(0)
    , max_pwm(0)
    , min_velocity(0.0)
    , max_velocity(0.0)  {
    }
  StartArduinoRequest_(const ContainerAllocator& _alloc)
    : min_pwm(0)
    , max_pwm(0)
    , min_velocity(0.0)
    , max_velocity(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _min_pwm_type;
  _min_pwm_type min_pwm;

   typedef uint8_t _max_pwm_type;
  _max_pwm_type max_pwm;

   typedef float _min_velocity_type;
  _min_velocity_type min_velocity;

   typedef float _max_velocity_type;
  _max_velocity_type max_velocity;





  typedef boost::shared_ptr< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartArduinoRequest_

typedef ::chusa_msgs::StartArduinoRequest_<std::allocator<void> > StartArduinoRequest;

typedef boost::shared_ptr< ::chusa_msgs::StartArduinoRequest > StartArduinoRequestPtr;
typedef boost::shared_ptr< ::chusa_msgs::StartArduinoRequest const> StartArduinoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/ros_code/src/chusa_odom/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd9153f2e7177a076039c36fa7c73a0c";
  }

  static const char* value(const ::chusa_msgs::StartArduinoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd9153f2e7177a07ULL;
  static const uint64_t static_value2 = 0x6039c36fa7c73a0cULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/StartArduinoRequest";
  }

  static const char* value(const ::chusa_msgs::StartArduinoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char min_pwm\n"
"char max_pwm\n"
"float32 min_velocity\n"
"float32 max_velocity\n"
;
  }

  static const char* value(const ::chusa_msgs::StartArduinoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_pwm);
      stream.next(m.max_pwm);
      stream.next(m.min_velocity);
      stream.next(m.max_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartArduinoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::StartArduinoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::StartArduinoRequest_<ContainerAllocator>& v)
  {
    s << indent << "min_pwm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.min_pwm);
    s << indent << "max_pwm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.max_pwm);
    s << indent << "min_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.min_velocity);
    s << indent << "max_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.max_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_STARTARDUINOREQUEST_H
