// Generated by gencpp from file chusa_msgs/StopArduino.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_STOPARDUINO_H
#define CHUSA_MSGS_MESSAGE_STOPARDUINO_H

#include <ros/service_traits.h>


#include <chusa_msgs/StopArduinoRequest.h>
#include <chusa_msgs/StopArduinoResponse.h>


namespace chusa_msgs
{

struct StopArduino
{

typedef StopArduinoRequest Request;
typedef StopArduinoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopArduino
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::StopArduino > {
  static const char* value()
  {
    return "3e0d6eb568f8fb312b5a1c787bc7c86f";
  }

  static const char* value(const ::chusa_msgs::StopArduino&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::StopArduino > {
  static const char* value()
  {
    return "chusa_msgs/StopArduino";
  }

  static const char* value(const ::chusa_msgs::StopArduino&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::StopArduinoRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::StopArduino > 
template<>
struct MD5Sum< ::chusa_msgs::StopArduinoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::StopArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StopArduinoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::StopArduinoRequest> should match 
// service_traits::DataType< ::chusa_msgs::StopArduino > 
template<>
struct DataType< ::chusa_msgs::StopArduinoRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::StopArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StopArduinoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::StopArduinoResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::StopArduino > 
template<>
struct MD5Sum< ::chusa_msgs::StopArduinoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::StopArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StopArduinoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::StopArduinoResponse> should match 
// service_traits::DataType< ::chusa_msgs::StopArduino > 
template<>
struct DataType< ::chusa_msgs::StopArduinoResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::StopArduino >::value();
  }
  static const char* value(const ::chusa_msgs::StopArduinoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_STOPARDUINO_H
