// Generated by gencpp from file chusa_msgs/StopArduinoRequest.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_STOPARDUINOREQUEST_H
#define CHUSA_MSGS_MESSAGE_STOPARDUINOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct StopArduinoRequest_
{
  typedef StopArduinoRequest_<ContainerAllocator> Type;

  StopArduinoRequest_()
    : tx_signal(false)  {
    }
  StopArduinoRequest_(const ContainerAllocator& _alloc)
    : tx_signal(false)  {
  (void)_alloc;
    }



   typedef uint8_t _tx_signal_type;
  _tx_signal_type tx_signal;





  typedef boost::shared_ptr< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopArduinoRequest_

typedef ::chusa_msgs::StopArduinoRequest_<std::allocator<void> > StopArduinoRequest;

typedef boost::shared_ptr< ::chusa_msgs::StopArduinoRequest > StopArduinoRequestPtr;
typedef boost::shared_ptr< ::chusa_msgs::StopArduinoRequest const> StopArduinoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/ros_code/src/chusa_odom/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fceae370fe7a9001d381957f0e8b868e";
  }

  static const char* value(const ::chusa_msgs::StopArduinoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfceae370fe7a9001ULL;
  static const uint64_t static_value2 = 0xd381957f0e8b868eULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/StopArduinoRequest";
  }

  static const char* value(const ::chusa_msgs::StopArduinoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool tx_signal\n"
;
  }

  static const char* value(const ::chusa_msgs::StopArduinoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tx_signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopArduinoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::StopArduinoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::StopArduinoRequest_<ContainerAllocator>& v)
  {
    s << indent << "tx_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tx_signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_STOPARDUINOREQUEST_H
