// Generated by gencpp from file chusa_msgs/Sensing3DOnce.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_SENSING3DONCE_H
#define CHUSA_MSGS_MESSAGE_SENSING3DONCE_H

#include <ros/service_traits.h>


#include <chusa_msgs/Sensing3DOnceRequest.h>
#include <chusa_msgs/Sensing3DOnceResponse.h>


namespace chusa_msgs
{

struct Sensing3DOnce
{

typedef Sensing3DOnceRequest Request;
typedef Sensing3DOnceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sensing3DOnce
} // namespace chusa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chusa_msgs::Sensing3DOnce > {
  static const char* value()
  {
    return "bbb7ba84302b6f35af5466a95cd7ac90";
  }

  static const char* value(const ::chusa_msgs::Sensing3DOnce&) { return value(); }
};

template<>
struct DataType< ::chusa_msgs::Sensing3DOnce > {
  static const char* value()
  {
    return "chusa_msgs/Sensing3DOnce";
  }

  static const char* value(const ::chusa_msgs::Sensing3DOnce&) { return value(); }
};


// service_traits::MD5Sum< ::chusa_msgs::Sensing3DOnceRequest> should match 
// service_traits::MD5Sum< ::chusa_msgs::Sensing3DOnce > 
template<>
struct MD5Sum< ::chusa_msgs::Sensing3DOnceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::Sensing3DOnce >::value();
  }
  static const char* value(const ::chusa_msgs::Sensing3DOnceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::Sensing3DOnceRequest> should match 
// service_traits::DataType< ::chusa_msgs::Sensing3DOnce > 
template<>
struct DataType< ::chusa_msgs::Sensing3DOnceRequest>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::Sensing3DOnce >::value();
  }
  static const char* value(const ::chusa_msgs::Sensing3DOnceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chusa_msgs::Sensing3DOnceResponse> should match 
// service_traits::MD5Sum< ::chusa_msgs::Sensing3DOnce > 
template<>
struct MD5Sum< ::chusa_msgs::Sensing3DOnceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chusa_msgs::Sensing3DOnce >::value();
  }
  static const char* value(const ::chusa_msgs::Sensing3DOnceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chusa_msgs::Sensing3DOnceResponse> should match 
// service_traits::DataType< ::chusa_msgs::Sensing3DOnce > 
template<>
struct DataType< ::chusa_msgs::Sensing3DOnceResponse>
{
  static const char* value()
  {
    return DataType< ::chusa_msgs::Sensing3DOnce >::value();
  }
  static const char* value(const ::chusa_msgs::Sensing3DOnceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_SENSING3DONCE_H
