// Generated by gencpp from file chusa_msgs/Tilt.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_TILT_H
#define CHUSA_MSGS_MESSAGE_TILT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct Tilt_
{
  typedef Tilt_<ContainerAllocator> Type;

  Tilt_()
    : tick(0)  {
    }
  Tilt_(const ContainerAllocator& _alloc)
    : tick(0)  {
  (void)_alloc;
    }



   typedef int32_t _tick_type;
  _tick_type tick;





  typedef boost::shared_ptr< ::chusa_msgs::Tilt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::Tilt_<ContainerAllocator> const> ConstPtr;

}; // struct Tilt_

typedef ::chusa_msgs::Tilt_<std::allocator<void> > Tilt;

typedef boost::shared_ptr< ::chusa_msgs::Tilt > TiltPtr;
typedef boost::shared_ptr< ::chusa_msgs::Tilt const> TiltConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::Tilt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::Tilt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/clear/src/chusa_msgs/msg', '/home/jaeho/clear/src/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::Tilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::Tilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::Tilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::Tilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::Tilt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::Tilt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::Tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcdef0b4cda8922f87070d3fba0b0dc8";
  }

  static const char* value(const ::chusa_msgs::Tilt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcdef0b4cda8922fULL;
  static const uint64_t static_value2 = 0x87070d3fba0b0dc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::Tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/Tilt";
  }

  static const char* value(const ::chusa_msgs::Tilt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::Tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tick\n"
;
  }

  static const char* value(const ::chusa_msgs::Tilt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::Tilt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tick);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tilt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::Tilt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::Tilt_<ContainerAllocator>& v)
  {
    s << indent << "tick: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tick);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_TILT_H
