// Generated by gencpp from file chusa_msgs/Pwm.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_PWM_H
#define CHUSA_MSGS_MESSAGE_PWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct Pwm_
{
  typedef Pwm_<ContainerAllocator> Type;

  Pwm_()
    : left_pwm(0)
    , right_pwm(0)  {
    }
  Pwm_(const ContainerAllocator& _alloc)
    : left_pwm(0)
    , right_pwm(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_pwm_type;
  _left_pwm_type left_pwm;

   typedef int32_t _right_pwm_type;
  _right_pwm_type right_pwm;





  typedef boost::shared_ptr< ::chusa_msgs::Pwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::Pwm_<ContainerAllocator> const> ConstPtr;

}; // struct Pwm_

typedef ::chusa_msgs::Pwm_<std::allocator<void> > Pwm;

typedef boost::shared_ptr< ::chusa_msgs::Pwm > PwmPtr;
typedef boost::shared_ptr< ::chusa_msgs::Pwm const> PwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::Pwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::Pwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/workspace/src/chusa_bringup/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::Pwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::Pwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49730b9392889d9a1a157054a0510db0";
  }

  static const char* value(const ::chusa_msgs::Pwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49730b9392889d9aULL;
  static const uint64_t static_value2 = 0x1a157054a0510db0ULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/Pwm";
  }

  static const char* value(const ::chusa_msgs::Pwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left_pwm\n"
"int32 right_pwm\n"
;
  }

  static const char* value(const ::chusa_msgs::Pwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::Pwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_pwm);
      stream.next(m.right_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::Pwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::Pwm_<ContainerAllocator>& v)
  {
    s << indent << "left_pwm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_pwm);
    s << indent << "right_pwm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_PWM_H
