// Generated by gencpp from file chusa_msgs/3DSensingOnceRequest.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_3DSENSINGONCEREQUEST_H
#define CHUSA_MSGS_MESSAGE_3DSENSINGONCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct 3DSensingOnceRequest_
{
  typedef 3DSensingOnceRequest_<ContainerAllocator> Type;

  3DSensingOnceRequest_()
    : start(false)  {
    }
  3DSensingOnceRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct 3DSensingOnceRequest_

typedef ::chusa_msgs::3DSensingOnceRequest_<std::allocator<void> > 3DSensingOnceRequest;

typedef boost::shared_ptr< ::chusa_msgs::3DSensingOnceRequest > 3DSensingOnceRequestPtr;
typedef boost::shared_ptr< ::chusa_msgs::3DSensingOnceRequest const> 3DSensingOnceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/pi/src/chusa_msgs/msg', '/home/jaeho/pi/src/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/3DSensingOnceRequest";
  }

  static const char* value(const ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct 3DSensingOnceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::3DSensingOnceRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_3DSENSINGONCEREQUEST_H
