// Generated by gencpp from file chusa_msgs/ResetTiltRequest.msg
// DO NOT EDIT!


#ifndef CHUSA_MSGS_MESSAGE_RESETTILTREQUEST_H
#define CHUSA_MSGS_MESSAGE_RESETTILTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chusa_msgs
{
template <class ContainerAllocator>
struct ResetTiltRequest_
{
  typedef ResetTiltRequest_<ContainerAllocator> Type;

  ResetTiltRequest_()
    : reset(false)  {
    }
  ResetTiltRequest_(const ContainerAllocator& _alloc)
    : reset(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetTiltRequest_

typedef ::chusa_msgs::ResetTiltRequest_<std::allocator<void> > ResetTiltRequest;

typedef boost::shared_ptr< ::chusa_msgs::ResetTiltRequest > ResetTiltRequestPtr;
typedef boost::shared_ptr< ::chusa_msgs::ResetTiltRequest const> ResetTiltRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chusa_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'chusa_msgs': ['/home/jaeho/clear/src/chusa_msgs/msg', '/home/jaeho/clear/src/chusa_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4b0b221fb425ac5eaf73f71ae34971";
  }

  static const char* value(const ::chusa_msgs::ResetTiltRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4b0b221fb425acULL;
  static const uint64_t static_value2 = 0x5eaf73f71ae34971ULL;
};

template<class ContainerAllocator>
struct DataType< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chusa_msgs/ResetTiltRequest";
  }

  static const char* value(const ::chusa_msgs::ResetTiltRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n"
;
  }

  static const char* value(const ::chusa_msgs::ResetTiltRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetTiltRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chusa_msgs::ResetTiltRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chusa_msgs::ResetTiltRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHUSA_MSGS_MESSAGE_RESETTILTREQUEST_H
